# Generated by Django 5.2.16 on 2026-07-21

import decimal

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0002_aviation_domain"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimulationClock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seed", models.BigIntegerField()),
                ("schedule_anchor", models.DateTimeField()),
                ("wall_clock_started_at", models.DateTimeField()),
                (
                    "speed_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=decimal.Decimal("1.00"),
                        max_digits=8,
                    ),
                ),
                ("paused", models.BooleanField(default=False)),
                ("paused_simulation_time", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=Q(("speed_multiplier__gt", 0)),
                        name="simulation_clock_speed_positive",
                    ),
                    models.CheckConstraint(
                        condition=(
                            Q(("paused", True), ("paused_simulation_time__isnull", False))
                            | Q(("paused", False), ("paused_simulation_time__isnull", True))
                        ),
                        name="simulation_clock_pause_state_consistent",
                    ),
                ],
            },
        ),
    ]
