# Generated by Django 5.2.16 on 2026-07-23 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_simulationclock'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('pilot', 'Pilot'), ('flight_attendant', 'Flight Attendant')], max_length=20)),
                ('profile_picture', models.ImageField(blank=True, help_text='Profile picture displayed on flight details and map markers.', null=True, upload_to='crew/pictures/')),
            ],
            options={
                'verbose_name': 'Crew member',
                'verbose_name_plural': 'Crew members',
                'ordering': ['last_name', 'first_name', 'role'],
            },
        ),
        migrations.CreateModel(
            name='FlightCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('crew_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_flights', to='tracker.crewmember')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_crew', to='tracker.flight')),
            ],
            options={
                'ordering': ['crew_member__last_name', 'crew_member__first_name'],
                'constraints': [models.UniqueConstraint(fields=('flight', 'crew_member'), name='unique_crew_flight_assignment')],
            },
        ),
    ]
