# Generated by Django 5.1.15 on 2026-07-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_add_crew_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewmember',
            name='profile_picture',
            field=models.CharField(blank=True, default='', help_text='Repository-local static path for crew profile avatar SVG.', max_length=255),
        ),
    ]
